env:
  WORKING_DIRECTORY: aspnet

jobs:
  build:
    name: build_aspnet
    runs-on: ubuntu-18.04
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2.1.0
      - name: dotnet_build
        run: dotnet build
        working-directory: ${{ env.WORKING_DIRECTORY }}

  test:
    name: test_job
    runs-on: ubuntu-18.04
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2.1.0
      - name: dotnet_test
        run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=../code_coverage/ -p:CoverletOutputFormat=opencover
        working-directory: ${{ env.WORKING_DIRECTORY }}

  analyze:
    name: analyze_job
    needs: [build, test]
    runs-on: ubuntu-18.04
    steps:
      - name: analyze_script
        run: echo 'analyze script'

  pack:
    name: pack_job
    needs: [analyze]
    runs-on: ubuntu-18.04
    steps:
      - name: pack_script
        run: echo 'pack script'

name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
